[Settings]
# use User's AppData folder for logs and configs
# usually C:\Users\<USERNAME>\AppData\Local\PixetPro (Windows)
UseAppDataDir=true

# Custom directories per user:
# AppDataDir=C:\myPixetAppData\group1
# ConfigsDir=C:\myPixetAppData\configsGroup1
# LogsDir=C:\myPixetAppData\logsGroup1

# Logging settings
LogRotateCount=10
LogToStdout=false
CApiLog=true

# Use of a virtual device when no device connected
CreateFileDeviceWhenNoDevs=false

[Hwlibs]
Hwlib=\Users\Aurelie\SoftDev\borealis\borealis\lib\pixet\minipix.dll
# Hwlib=\Users\Aurelie\SoftDev\borealis\borealis\lib\pixet\dummy.dll
