title: Borealis
description: Documentation for the Borealis project

remote_theme: just-the-docs/just-the-docs

titles_from_headings:
  enabled: true

###############################
# Just-the-docs configuration #
###############################

# Enable or disable the side/mobile menu globally
nav_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Borealis on GitHub":
    - "https://github.com/avancra/Borealis"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# External navigation links
nav_external_links:
  - title: Borealis on GitHub
    url: https://github.com/avancra/Borealis
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Add support for LaTeX rendering of mathematical equation
math: mathjax
